FROM mysql:8.0.33
LABEL "Project"="Vprofile"
LABEL "Author"="Paras"

ENV MYSQL_ROOT_PASSWORD="vprodbpass"
ENV MYSQL_DATABASE="accounts"

ADD db_backup.sql /home/paras8x24/DevOps/docker-engine/vprofile-project/Docker-files/db/db_backup.sql